# Generated by Django 6.1.1 on 2026-09-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_agb_accepted_customuser_agb_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agb_accepted',
            field=models.BooleanField(default=False, verbose_name='AGB akzeptiert'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agb_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AGB akzeptiert am'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Datenschutzerklärung akzeptiert'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datenschutzerklärung akzeptiert am'),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
