# Generated by Django 6.1.1 on 2026-09-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_agb_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='is_used',
        ),
    ]
