# Generated by Django 6.1.1 on 2026-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emailverificationcode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
