# Generated by Django 6.1.1 on 2026-09-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'verbose_name': 'E-Mail-Verifizierungscode', 'verbose_name_plural': 'E-Mail-Verifizierungscodes'},
        ),
    ]
